web: cd src && python manage.py migrate --noinput && python manage.py collectstatic --noinput && gunicorn config.asgi:application --worker-class uvicorn.workers.UvicornWorker --workers 3 --timeout 120 --bind 0.0.0.0:$PORT
worker: cd src && celery -A config worker --loglevel=info --pool=solo
beat: cd src && celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
