# Generated by Django 5.0.6 on 2026-03-04 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('current_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('volume_24h', models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True)),
                ('price_change_24h', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Activo Criptográfico',
                'verbose_name_plural': 'Activos Criptográficos',
                'db_table': 'crypto_assets',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='AnalysisExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'En ejecución'), ('completed', 'Completado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='core.cryptoasset')),
            ],
            options={
                'verbose_name': 'Ejecución de Análisis',
                'verbose_name_plural': 'Ejecuciones de Análisis',
                'db_table': 'analysis_executions',
            },
        ),
        migrations.CreateModel(
            name='MarketDataSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=2, max_digits=30)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='core.cryptoasset')),
            ],
            options={
                'verbose_name': 'Snapshot de Mercado',
                'verbose_name_plural': 'Snapshots de Mercado',
                'db_table': 'market_data_snapshots',
                'ordering': ['-timestamp'],
            },
        ),
    ]
