# Generated by Django 5.0.6 on 2026-03-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, help_text='True cuando el usuario finaliza el setup de 2FA.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='True cuando el usuario confirma su email.'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Clave secreta TOTP (base32). Null si 2FA no está configurado.', max_length=64, null=True),
        ),
    ]
