# Generated by Django 5.0.6 on 2026-03-14 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_auth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoasset',
            name='asset_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='coingecko_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='decimals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='ath',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='ath_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='atl',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='atl_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='circulating_supply',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='fully_diluted_valuation',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='max_supply',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=38, null=True),
        ),
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='price_change_24h_pct',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='price_change_30d_pct',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='price_change_7d_pct',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='marketdatasnapshot',
            name='total_supply',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=38, null=True),
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=18, max_digits=38)),
                ('purchase_value_usd', models.DecimalField(decimal_places=18, max_digits=38)),
                ('current_value_usd', models.DecimalField(blank=True, decimal_places=18, max_digits=38, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_entries', to='core.cryptoasset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Posición de Portfolio',
                'verbose_name_plural': 'Posiciones de Portfolio',
                'db_table': 'portfolio_assets',
            },
        ),
        migrations.AddConstraint(
            model_name='portfolioasset',
            constraint=models.UniqueConstraint(fields=('user', 'asset'), name='uq_portfolio_asset_user_asset'),
        ),
    ]
