# Generated by Django 5.0.6 on 2026-04-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_portfolio_and_expand_market_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('admin', 'Administrador')], db_index=True, default='user', help_text="Rol del usuario en el sistema: 'user' o 'admin'.", max_length=10),
        ),
    ]
