# Generated by Django 5.0.6 on 2026-06-16 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_user_pending_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("spec", models.JSONField()),
                ("spec_hash", models.CharField(db_index=True, max_length=64)),
                ("interval", models.CharField(default="1d", max_length=10)),
                ("rank", models.PositiveSmallIntegerField(default=0)),
                ("fitness", models.FloatField(blank=True, null=True)),
                ("passed_gating", models.BooleanField(default=False)),
                ("robustness_metrics", models.JSONField(blank=True, null=True)),
                ("gating_checks", models.JSONField(blank=True, null=True)),
                ("holdout_metrics", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("candidate", "Candidata"),
                            ("validated", "Validada"),
                            ("rejected", "Descartada"),
                            ("archived", "Archivada"),
                        ],
                        default="candidate",
                        max_length=20,
                    ),
                ),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_definitions",
                        to="core.cryptoasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estrategia Generada",
                "verbose_name_plural": "Estrategias Generadas",
                "db_table": "strategy_definitions",
                "ordering": ["rank", "-fitness"],
                "indexes": [
                    models.Index(
                        fields=["asset", "interval", "status"],
                        name="strategy_de_asset_i_76f8b3_idx",
                    )
                ],
            },
        ),
    ]
