# Generated by Django 5.0.6 on 2026-08-02 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_user_pending_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "actor_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login.success", "Inicio de sesión correcto"),
                            ("login.failure", "Inicio de sesión fallido"),
                            ("login.blocked", "Inicio de sesión bloqueado"),
                            ("logout", "Cierre de sesión"),
                            ("2fa.challenge", "Segundo factor solicitado"),
                            ("2fa.success", "Segundo factor superado"),
                            ("2fa.failure", "Segundo factor fallido"),
                            ("2fa.enabled", "Doble factor activado"),
                            ("2fa.disabled", "Doble factor desactivado"),
                            (
                                "2fa.recovery_regenerated",
                                "Códigos de recuperación regenerados",
                            ),
                            ("account.register", "Registro de cuenta"),
                            ("account.email_verified", "Email verificado"),
                            ("account.password_changed", "Contraseña cambiada"),
                            ("account.password_reset", "Contraseña restablecida"),
                            (
                                "account.email_change_requested",
                                "Cambio de email solicitado",
                            ),
                            ("account.email_changed", "Email cambiado"),
                            ("account.deleted", "Cuenta eliminada"),
                            ("admin.user_created", "Usuario administrador creado"),
                            (
                                "admin.user_updated",
                                "Usuario modificado por un administrador",
                            ),
                            ("admin.market_sync", "Sincronización de mercado forzada"),
                        ],
                        db_index=True,
                        max_length=48,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[("SUCCESS", "Correcto"), ("FAILURE", "Fallido")],
                        default="SUCCESS",
                        max_length=8,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user_agent",
                    models.CharField(blank=True, default="", max_length=400),
                ),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Registro de auditoría",
                "verbose_name_plural": "Registros de auditoría",
                "db_table": "audit_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="credentials_changed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Momento del último cambio de credenciales (contraseña, email o doble factor). Todo JWT emitido antes de esta marca se rechaza: es lo que hace que cambiar la contraseña expulse de verdad a las sesiones abiertas.",
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="marketdatasnapshot",
            index=models.Index(
                fields=["asset", "-timestamp"], name="idx_snapshot_asset_ts"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(
                fields=["user", "status", "-opened_at"], name="idx_position_user_status"
            ),
        ),
        migrations.AddIndex(
            model_name="pricealert",
            index=models.Index(
                fields=["user", "-created_at"], name="idx_alert_user_created"
            ),
        ),
        migrations.AddIndex(
            model_name="pricealert",
            index=models.Index(
                fields=["is_active", "is_triggered"], name="idx_alert_pending"
            ),
        ),
        migrations.AddIndex(
            model_name="tradehistory",
            index=models.Index(
                fields=["user", "-executed_at"], name="idx_trade_user_executed"
            ),
        ),
        migrations.AddIndex(
            model_name="tradehistory",
            index=models.Index(fields=["position"], name="idx_trade_position"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor", "-created_at"], name="idx_audit_actor_created"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["action", "-created_at"], name="idx_audit_action_created"
            ),
        ),
    ]
