# Generated by Django 5.0.6 on 2026-06-16 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_strategydefinition"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategydefinition",
            name="is_monitored",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="strategydefinition",
            name="last_signal",
            field=models.CharField(default="HOLD", max_length=8),
        ),
        migrations.AddField(
            model_name="strategydefinition",
            name="last_signal_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="strategydefinition",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monitored_strategies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
