# Generated by Django 5.0.6 on 2026-06-16 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_strategydefinition_is_monitored_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategySignalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        choices=[("BUY", "Compra"), ("SELL", "Venta")], max_length=8
                    ),
                ),
                ("price", models.FloatField(blank=True, null=True)),
                ("notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategy_signal_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signal_events",
                        to="core.strategydefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento de Señal",
                "verbose_name_plural": "Eventos de Señal",
                "db_table": "strategy_signal_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="strategy_si_owner_i_3dd090_idx",
                    )
                ],
            },
        ),
    ]
