# Generated by Django 5.0.6 on 2026-06-20 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_strategysignalevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_symbol", models.CharField(db_index=True, max_length=20)),
                ("interval", models.CharField(max_length=10)),
                ("horizon", models.PositiveSmallIntegerField()),
                (
                    "predicted",
                    models.CharField(
                        choices=[("ALCISTA", "Alcista"), ("BAJISTA", "Bajista")],
                        max_length=8,
                    ),
                ),
                ("prob_up", models.FloatField()),
                ("confidence", models.FloatField()),
                ("edge", models.FloatField(blank=True, null=True)),
                ("oos_accuracy", models.FloatField(blank=True, null=True)),
                ("verdict", models.CharField(blank=True, max_length=10)),
                ("model", models.CharField(blank=True, max_length=80)),
                ("price_at_prediction", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("correct", "Acierto"),
                            ("incorrect", "Fallo"),
                            ("unresolved", "Sin resolver"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("resolve_at", models.DateTimeField(db_index=True)),
                (
                    "actual_direction",
                    models.CharField(
                        blank=True,
                        choices=[("ALCISTA", "Alcista"), ("BAJISTA", "Bajista")],
                        max_length=8,
                    ),
                ),
                ("price_at_resolution", models.FloatField(blank=True, null=True)),
                ("actual_return_pct", models.FloatField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prediction_records",
                        to="core.cryptoasset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro de Predicción",
                "verbose_name_plural": "Registros de Predicción",
                "db_table": "prediction_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "resolve_at"],
                        name="prediction__status_32822f_idx",
                    ),
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="prediction__owner_i_1cdf0e_idx",
                    ),
                    models.Index(
                        fields=["asset_symbol", "-created_at"],
                        name="prediction__asset_s_3d7dbb_idx",
                    ),
                ],
            },
        ),
    ]
