# Generated by Django 5.0.6 on 2026-06-21 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_predictionrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaperTradingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_symbol", models.CharField(db_index=True, max_length=20)),
                ("interval", models.CharField(default="1d", max_length=10)),
                ("initial_capital", models.FloatField(default=10000.0)),
                ("cash", models.FloatField(default=10000.0)),
                ("units", models.FloatField(default=0.0)),
                ("entry_price", models.FloatField(blank=True, null=True)),
                ("last_price", models.FloatField(blank=True, null=True)),
                ("realized_pnl", models.FloatField(default=0.0)),
                ("commission_bps", models.FloatField(default=10.0)),
                ("slippage_bps", models.FloatField(default=5.0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("trades_count", models.PositiveIntegerField(default=0)),
                ("wins", models.PositiveIntegerField(default=0)),
                ("last_signal", models.CharField(default="HOLD", max_length=8)),
                ("last_eval_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paper_accounts",
                        to="core.strategydefinition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cartera de Paper Trading",
                "verbose_name_plural": "Carteras de Paper Trading",
                "db_table": "paper_trading_accounts",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PaperTrade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Compra"), ("SELL", "Venta")], max_length=4
                    ),
                ),
                ("price", models.FloatField()),
                ("fill_price", models.FloatField()),
                ("units", models.FloatField()),
                ("cost", models.FloatField(default=0.0)),
                ("cash_after", models.FloatField()),
                ("equity_after", models.FloatField()),
                ("pnl", models.FloatField(blank=True, null=True)),
                ("pnl_pct", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="core.papertradingaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operación de Paper Trading",
                "verbose_name_plural": "Operaciones de Paper Trading",
                "db_table": "paper_trades",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="papertradingaccount",
            index=models.Index(
                fields=["owner", "is_active"], name="paper_tradi_owner_i_d8a392_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="papertradingaccount",
            index=models.Index(
                fields=["is_active", "asset_symbol", "interval"],
                name="paper_tradi_is_acti_b84925_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="papertrade",
            index=models.Index(
                fields=["account", "-created_at"], name="paper_trade_account_e7e7fc_idx"
            ),
        ),
    ]
