# Generated by Django 5.0.6 on 2026-06-21 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_paper_trading"),
    ]

    operations = [
        migrations.AddField(
            model_name="papertradingaccount",
            name="decayed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="papertradingaccount",
            name="decayed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="papertradingaccount",
            name="peak_equity",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="PaperEquitySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equity", models.FloatField()),
                ("price", models.FloatField()),
                ("in_position", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equity_snapshots",
                        to="core.papertradingaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapshot de Patrimonio",
                "verbose_name_plural": "Snapshots de Patrimonio",
                "db_table": "paper_equity_snapshots",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "created_at"],
                        name="paper_equit_account_22cd71_idx",
                    )
                ],
            },
        ),
    ]
