# Generated by Django 5.0.6 on 2026-06-24 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_paper_equity_curve_decay"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=42)),
                ("label", models.CharField(blank=True, max_length=80)),
                ("native_symbol", models.CharField(blank=True, max_length=10)),
                ("alert_threshold_pct", models.FloatField(default=5.0)),
                ("last_balance", models.FloatField(blank=True, null=True)),
                ("last_value_usd", models.FloatField(blank=True, null=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watched_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección Vigilada",
                "verbose_name_plural": "Direcciones Vigiladas",
                "db_table": "watched_addresses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AddressAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("increase", "Entrada"), ("decrease", "Salida")],
                        max_length=10,
                    ),
                ),
                ("balance_before", models.FloatField()),
                ("balance_after", models.FloatField()),
                ("delta", models.FloatField()),
                ("delta_pct", models.FloatField()),
                ("value_usd", models.FloatField(blank=True, null=True)),
                ("notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "watched",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="core.watchedaddress",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta de Dirección",
                "verbose_name_plural": "Alertas de Dirección",
                "db_table": "address_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="watchedaddress",
            index=models.Index(
                fields=["owner", "-created_at"], name="watched_add_owner_i_bb3b77_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="watchedaddress",
            constraint=models.UniqueConstraint(
                fields=("owner", "chain", "address"),
                name="uniq_watched_owner_chain_address",
            ),
        ),
        migrations.AddIndex(
            model_name="addressalert",
            index=models.Index(
                fields=["owner", "-created_at"], name="address_ale_owner_i_e3829c_idx"
            ),
        ),
    ]
