# Generated by Django 5.0.6 on 2026-06-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_watchlist_alerts"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notifications_seen_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Última vez que el usuario abrió el centro de notificaciones; los eventos posteriores cuentan como no leídos.",
                null=True,
            ),
        ),
    ]
