# Generated by Django 5.0.6 on 2026-07-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_user_notifications_seen_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhaleMovementSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain", models.CharField(db_index=True, max_length=20)),
                ("symbol", models.CharField(max_length=20)),
                ("kind", models.CharField(default="native", max_length=10)),
                ("amount", models.FloatField()),
                ("value_usd", models.FloatField(db_index=True)),
                ("from_address", models.CharField(blank=True, max_length=64)),
                ("to_address", models.CharField(blank=True, max_length=64)),
                ("from_label", models.CharField(blank=True, max_length=120)),
                ("to_label", models.CharField(blank=True, max_length=120)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("to_exchange", "Depósito en exchange"),
                            ("from_exchange", "Retirada de exchange"),
                            ("between_exchanges", "Entre exchanges"),
                            ("unknown", "Desconocida"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("tx_hash", models.CharField(max_length=80)),
                ("moved_at", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Movimiento de Ballena",
                "verbose_name_plural": "Movimientos de Ballena",
                "db_table": "whale_movement_snapshots",
                "ordering": ["-moved_at"],
                "indexes": [
                    models.Index(
                        fields=["chain", "-moved_at"],
                        name="whale_movem_chain_5fdaf1_idx",
                    ),
                    models.Index(
                        fields=["direction", "-moved_at"],
                        name="whale_movem_directi_4265e7_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="whalemovementsnapshot",
            constraint=models.UniqueConstraint(
                fields=("chain", "tx_hash", "symbol", "from_address", "to_address"),
                name="uniq_whale_movement",
            ),
        ),
    ]
