# Generated by Django 5.0.6 on 2026-07-02 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_whale_movement_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("binance", "Binance"),
                            ("kraken", "Kraken"),
                            ("coinbase", "Coinbase Advanced"),
                            ("bybit", "Bybit"),
                            ("okx", "OKX"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=80)),
                ("api_key_enc", models.TextField()),
                ("api_secret_enc", models.TextField()),
                ("api_password_enc", models.TextField(blank=True, default="")),
                ("is_testnet", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conexión de Exchange",
                "verbose_name_plural": "Conexiones de Exchange",
                "db_table": "exchange_connections",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["owner", "is_active"],
                        name="exchange_co_owner_i_077439_idx",
                    )
                ],
            },
        ),
    ]
