# Generated by Django 5.0.6 on 2026-07-02 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_exchange_connections"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnChainSignalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain", models.CharField(db_index=True, max_length=20)),
                ("verdict", models.CharField(max_length=20)),
                ("previous_verdict", models.CharField(blank=True, max_length=20)),
                ("pressure", models.FloatField()),
                ("window_hours", models.PositiveSmallIntegerField(default=24)),
                ("inflow_usd", models.FloatField(default=0.0)),
                ("outflow_usd", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Señal On-Chain",
                "verbose_name_plural": "Señales On-Chain",
                "db_table": "onchain_signal_events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["chain", "-created_at"],
                        name="onchain_sig_chain_867bc8_idx",
                    )
                ],
            },
        ),
    ]
