# Generated by Django 5.0.6 on 2026-07-02 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_onchain_signal_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="papertradingaccount",
            name="live_base_position",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="papertradingaccount",
            name="live_cap_usd",
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name="papertradingaccount",
            name="live_connection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="live_paper_accounts",
                to="core.exchangeconnection",
            ),
        ),
        migrations.AddField(
            model_name="papertradingaccount",
            name="live_enabled",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="papertradingaccount",
            name="live_error",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
