# Generated by Django 5.0.6 on 2026-07-02 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_paper_live_promotion"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveOrderRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=20)),
                ("side", models.CharField(max_length=4)),
                ("amount", models.FloatField()),
                ("ref_price", models.FloatField()),
                ("fill_price", models.FloatField(blank=True, null=True)),
                ("notional_usd", models.FloatField(default=0.0)),
                ("is_testnet", models.BooleanField(default=True)),
                (
                    "broker_order_id",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Enviada"), ("failed", "Fallida")],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("error", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_orders",
                        to="core.papertradingaccount",
                    ),
                ),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="live_orders",
                        to="core.exchangeconnection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden Real (auditoría)",
                "verbose_name_plural": "Órdenes Reales (auditoría)",
                "db_table": "live_order_records",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "-created_at"],
                        name="live_order__account_91897f_idx",
                    )
                ],
            },
        ),
    ]
