# Generated by Django 5.0.6 on 2026-07-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_live_order_records"),
    ]

    operations = [
        migrations.AddField(
            model_name="papertradingaccount",
            name="live_disabled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
