# Generated by Django 5.0.6 on 2026-07-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_paper_live_disabled_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="OhlcvCandle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("interval", models.CharField(max_length=8)),
                ("open_time", models.BigIntegerField()),
                ("open", models.FloatField()),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.FloatField()),
                ("source", models.CharField(default="binance", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Vela OHLCV",
                "verbose_name_plural": "Velas OHLCV",
                "db_table": "ohlcv_candles",
                "indexes": [
                    models.Index(
                        fields=["symbol", "interval", "-open_time"],
                        name="ohlcv_candl_symbol_b96c1b_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="ohlcvcandle",
            constraint=models.UniqueConstraint(
                fields=("symbol", "interval", "open_time"), name="uq_ohlcv_candle"
            ),
        ),
    ]
