# Generated by Django 5.0.6 on 2026-07-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_ohlcv_candles"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfluenceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_symbol", models.CharField(db_index=True, max_length=20)),
                ("scores", models.JSONField(default=dict)),
                ("fused_score", models.FloatField()),
                ("verdict", models.CharField(max_length=30)),
                ("price_at", models.FloatField()),
                ("horizon_hours", models.PositiveIntegerField(default=24)),
                ("resolve_at", models.DateTimeField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pendiente"), ("resolved", "Resuelta")],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("actual_return_pct", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lectura de confluencia",
                "verbose_name_plural": "Lecturas de confluencia",
                "db_table": "confluence_snapshots",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "resolve_at"],
                        name="confluence__status_dea854_idx",
                    )
                ],
            },
        ),
    ]
