# Generated by Django 5.0.6 on 2026-07-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_confluence_snapshots"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfluenceSignalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("asset_symbol", models.CharField(db_index=True, max_length=20)),
                ("verdict", models.CharField(max_length=30)),
                (
                    "previous_verdict",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("score", models.FloatField()),
                ("agreement_pct", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "Evento de confluencia",
                "verbose_name_plural": "Eventos de confluencia",
                "db_table": "confluence_signal_events",
                "ordering": ["-created_at"],
            },
        ),
    ]
