# Generated by Django 5.0.6 on 2026-07-07 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_confluence_signal_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveRiskPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("daily_loss_limit_usd", models.FloatField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="live_risk_policy",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Política de riesgo en vivo",
                "verbose_name_plural": "Políticas de riesgo en vivo",
                "db_table": "live_risk_policies",
            },
        ),
    ]
