# Generated by Django 5.0.6 on 2026-07-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_oms_risk_reconciliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="papertradingaccount",
            name="live_discrepancy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="papertradingaccount",
            name="live_reconciled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
