# Generated by Django 5.0.6 on 2026-07-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_live_reconciliation_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liveorderrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("sent", "Enviada"),
                    ("failed", "Fallida"),
                    ("blocked", "Bloqueada"),
                ],
                db_index=True,
                max_length=10,
            ),
        ),
    ]
