# Generated by Django 5.0.6 on 2026-07-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_liveorder_blocked_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="liveriskpolicy",
            name="max_concentration_pct",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
