# Generated by Django 5.0.6 on 2026-07-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_push_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_risk_digest",
            field=models.BooleanField(
                default=False,
                help_text="Recibir un resumen diario del riesgo de la cartera (VaR, barreras del OMS y P&L) por email.",
            ),
        ),
    ]
