# Generated by Django 5.0.6 on 2026-07-24 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_notify_risk_digest"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuantAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric", models.CharField(max_length=40)),
                ("timeframe", models.CharField(default="1h", max_length=4)),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("gt", "Mayor o igual que"),
                            ("lt", "Menor que"),
                            ("cross_up", "Cruza al alza"),
                            ("cross_down", "Cruza a la baja"),
                        ],
                        max_length=10,
                    ),
                ),
                ("threshold", models.FloatField()),
                ("cooldown_minutes", models.PositiveIntegerField(default=60)),
                ("is_active", models.BooleanField(default=True)),
                ("last_side", models.CharField(blank=True, default="", max_length=6)),
                ("last_value", models.FloatField(blank=True, null=True)),
                ("last_fired_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quant_alerts",
                        to="core.cryptoasset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quant_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerta Cuantitativa",
                "verbose_name_plural": "Alertas Cuantitativas",
                "db_table": "quant_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuantAlertFiring",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fired_at", models.DateTimeField(auto_now_add=True)),
                ("value", models.FloatField()),
                ("threshold", models.FloatField()),
                ("operator", models.CharField(max_length=10)),
                ("message", models.CharField(max_length=300)),
                ("seen", models.BooleanField(default=False)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firings",
                        to="core.quantalert",
                    ),
                ),
            ],
            options={
                "verbose_name": "Disparo de Alerta Cuantitativa",
                "verbose_name_plural": "Disparos de Alertas Cuantitativas",
                "db_table": "quant_alert_firings",
                "ordering": ["-fired_at"],
            },
        ),
    ]
