# Generated by Django 5.0.6 on 2026-08-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_strategy_experiment_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="cryptoasset",
            name="delisted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Fin de cotización. Nulo = sigue vivo.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cryptoasset",
            name="delisting_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("delisted", "Retirado del exchange"),
                    ("dead", "Proyecto abandonado"),
                    ("merged", "Fusionado con otro activo"),
                    ("renamed", "Renombrado / redenominado"),
                ],
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cryptoasset",
            name="listed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Inicio de cotización. Antes de esta fecha el activo no era operable.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="FundingRateRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("funding_time", models.BigIntegerField()),
                ("funding_rate", models.FloatField()),
                ("mark_price", models.FloatField(blank=True, null=True)),
                ("interval_hours", models.PositiveSmallIntegerField(default=8)),
                ("source", models.CharField(default="binance", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tasa de financiación",
                "verbose_name_plural": "Tasas de financiación",
                "db_table": "funding_rate_records",
                "indexes": [
                    models.Index(
                        fields=["symbol", "-funding_time"],
                        name="funding_rat_symbol_0597e1_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="fundingraterecord",
            constraint=models.UniqueConstraint(
                fields=("symbol", "funding_time"), name="uq_funding_rate"
            ),
        ),
    ]
