# Generated by Django 5.0.6 on 2026-08-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_funding_and_asset_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChainMetricPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain", models.CharField(db_index=True, max_length=20)),
                ("metric", models.CharField(max_length=40)),
                ("timestamp", models.BigIntegerField()),
                ("value", models.FloatField()),
                ("source", models.CharField(default="blockscout", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Punto de métrica on-chain",
                "verbose_name_plural": "Puntos de métricas on-chain",
                "db_table": "chain_metric_points",
                "indexes": [
                    models.Index(
                        fields=["chain", "metric", "-timestamp"],
                        name="chain_metri_chain_86319f_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="chainmetricpoint",
            constraint=models.UniqueConstraint(
                fields=("chain", "metric", "timestamp"), name="uq_chain_metric_point"
            ),
        ),
    ]
