# Generated by Django 5.0.6 on 2026-09-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_strategysignalevent_signal"),
    ]

    operations = [
        migrations.CreateModel(
            name="DerivativeMetricPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(db_index=True, max_length=20)),
                ("venue", models.CharField(default="binance", max_length=20)),
                ("metric", models.CharField(max_length=40)),
                ("observed_at", models.BigIntegerField()),
                ("value", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Punto de Métrica de Derivados",
                "verbose_name_plural": "Puntos de Métricas de Derivados",
                "db_table": "derivative_metric_points",
                "ordering": ["observed_at"],
                "indexes": [
                    models.Index(
                        fields=["symbol", "metric", "observed_at"],
                        name="derivative__symbol_2a0a86_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="derivativemetricpoint",
            constraint=models.UniqueConstraint(
                fields=("symbol", "venue", "metric", "observed_at"),
                name="uniq_derivative_metric_point",
            ),
        ),
    ]
